### ISSUE TITLE
Event driven dank upload

### ISSUE THREAD

**Issue by willpoorman** [michaelhillebrand/huskiebot#26]
I'm good with this. Though I'd like to propose another option to consider implementing down the road: Event driven dank upload. Just auto save the image whenever someone uploads is. Send them a DM confirming their post was uploaded successfully when it's complete

_Originally posted by @willpoorman in https://github.com/michaelhillebrand/huskiebot/pull/25#issuecomment-596147132_

**Comment by michaelhillebrand** [comment]
#28 Has fixed this issue
